mixed-port: 7890
allow-lan: true
mode: rule
log-level: info

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
  fallback:
    - tls://dns.google

proxies:
  - name: è‡ªå»º-VPS-ç¾å›½
    type: vmess
    server: us.qijiaqiao.top
    port: 443
    uuid: 5609eeed-9f37-4460-f881-bfc515553baa
    alterId: 0
    cipher: auto
    network: ws
    ws-opts:
      path: /5609eeed
      headers:
        Host: us.qijiaqiao.top
    tls: true
    skip-cert-verify: false
    udp: true

proxy-providers:
  æœºåœºè®¢é˜…:
    type: http
    url: "https://zhuzhuzhu.whtjdasha.com/api/v1/client/subscribe?token=f9d4249f07dc88f07998387e00a9f197"
    path: ./æœºåœºè®¢é˜….yaml
    interval: 480
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: é»˜è®¤ä»£ç†
    type: select
    proxies:
      - è‡ªå»º-VPS-ç¾å›½
      - æœºåœº-æ¸¯æ¾³å°æœ€å¿«

  - name: æœºåœº-æ¸¯æ¾³å°æœ€å¿«
    type: url-test
    use:
      - æœºåœºè®¢é˜…
    filter:
      - 'é¦™æ¸¯|ğŸ‡­ğŸ‡°|HK'
      - 'å°æ¹¾|ğŸ‡¹ğŸ‡¼|TW'
      - 'æ–°åŠ å¡|ğŸ‡¸ğŸ‡¬|SG'
    proxies: []
    url: http://www.gstatic.com/generate_204
    interval: 180
    tolerance: 50
    lazy: true

rules:
  - GEOIP,CN,DIRECT
  - GEOSITE,cn,DIRECT
  - MATCH,é»˜è®¤ä»£ç†
